name: Deploy to ECS on AWS with Terraform

on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: my-ecr-repo
          DOCKERFILE_PATH: ./Dockerfile
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest $DOCKERFILE_PATH
          docker login -u AWS -p $(aws ecr get-login-password --region us-west-2) $ECR_REGISTRY
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS Cred
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/dev-ecs-role

      # Step 3: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 4: Plan Terraform
      - name: Plan Terraform
        run: terraform plan

      # Step 5: Apply Terraform
      - name: Apply Terraform
        run: terraform apply -auto-approve
